# Site settings
title: Jared Pendergraft
description: The personal website of Jared Pendergraft
keywords: jared pendergraft, jared pendergraft designs, design, website, graphic design hawaii, web design hawaii, graphic design maui, web design maui
baseurl: ''
url: 'http://jaredpendergraft.com'
twitter: 'jaredpdesigns'
email: 'hello@jaredpendergraft.com'
keep_files: [.git, 'CNAME']
exclude: ['README.md']
source: src
destination: docs

collections:
  projects:
    output: true
    permalink: /projects/:path
    
  snippets:
    output: true
    permalink: /snippets/:categories/:title
    
  clients:
    output: true
    permalink: /clients/:categories/:title
    
# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css/pasta
  style: compressed

# Outputting
permalink: /:categories/:title
paginate_path: /page:num

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  
# Autoprefixer
autoprefixer:
  browsers:
  - last 2 versions

gems:
- jekyll-autoprefixer
- jekyll-sitemap