# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jared Pendergraft
description: The personal website of Jared Pendergraft
keywords: jared pendergraft, jared pendergraft designs, design, website, graphic design hawaii, web design hawaii, graphic design maui, web design maui
baseurl: "" # For Github: "/jpd"
url: "http://jaredpendergraft.com/" # For Github: "http://jaredpdesigns.github.io/jpd/"
twitter: "jaredpdesigns"
email: "hello@jaredpendergraft.com"
keep_files: [".git, CNAME"]
exclude: ["README.md"]
source: src
destination: build

collections:
  projects:
    output: true
    permalink: /projects/:path
    
  snippets:
    output: true
    permalink: /snippets/:categories/:title
    
  clients:
    output: true
    permalink: /clients/:categories/:title
    
# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css/_partials

# Outputting
permalink: /:categories/:title
paginate_path: /page:num

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

gems:
- octopress-autoprefixer